version: '2.1'
services:
  db:
    image: willh/mssql-server-windows-developer:1809
    environment:
      sa_password: "Pa$$$$w0rd1234"
      ACCEPT_EULA: "Y"
      attach_dbs: "[{'dbName':'ContosoUniversity','dbFiles':['C:\\\\DB\\\\ContosoUniversity.mdf','C:\\\\DB\\\\ContosoUniversity_log.ldf']}]"
    volumes:
      - G:/Projects/DB:C:/DB
    ports:
      - "1433:1433"
  web:
    build:
      context: iis-mvc
      dockerfile: Dockerfile
    ports:
      - "80:80"

networks:
  default:
    external:
      name: nat